---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      day: 14
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
      day: 14
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      day: 14